# Generated by Django 5.1.3 on 2025-03-06 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_rename_cat_text_cat_cat_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specie_name', models.CharField(default='None', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_name',
            field=models.CharField(default='No Catitos', max_length=200),
        ),
        migrations.AddField(
            model_name='cat',
            name='specie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cats.specie'),
            preserve_default=False,
        ),
    ]
