# Generated by Django 5.1.3 on 2025-03-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_specie_alter_cat_cat_name_cat_specie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specie',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='specie',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='specie_name',
            new_name='type_name',
        ),
    ]
