# Generated by Django 5.1.3 on 2025-03-19 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_treat'),
    ]

    operations = [
        migrations.AddField(
            model_name='treat',
            name='treat_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
